// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package Java.eventgadget;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface DataServiceServant {

	 int hasUser(@TarsMethodParameter(name="wx_id")String wx_id, @TarsHolder(name="userExist") Holder<java.lang.Boolean> userExist);

	 int hasPhone(@TarsMethodParameter(name="phone")String phone, @TarsHolder(name="phoneExist") Holder<java.lang.Boolean> phoneExist);

	 int createUser(@TarsMethodParameter(name="wx_id")String wx_id, @TarsMethodParameter(name="userInfo")UserInfo userInfo);

	 int getUserInfo(@TarsMethodParameter(name="wx_id")String wx_id, @TarsHolder(name="userInfo") Holder<UserInfo> userInfo);

	 int getPlanetList(@TarsMethodParameter(name="index")int index, @TarsMethodParameter(name="batch")int batch, @TarsMethodParameter(name="wx_id")String wx_id, @TarsHolder(name="nextIndex") Holder<java.lang.Integer> nextIndex, @TarsHolder(name="planetInfoList") Holder<java.util.List<PlanetInfo>> planetInfoList);

	 int createProposal(@TarsMethodParameter(name="proposalInfo")ProposalInfo proposalInfo);

	 int getProposalList(@TarsMethodParameter(name="index")int index, @TarsMethodParameter(name="batch")int batch, @TarsMethodParameter(name="wx_id")String wx_id, @TarsMethodParameter(name="planet_id")String planet_id, @TarsHolder(name="nextIndex") Holder<java.lang.Integer> nextIndex, @TarsHolder(name="proposalList") Holder<java.util.List<java.util.Map<String, String>>> proposalList);

	 int updateProposal(@TarsMethodParameter(name="proposalInfo")ProposalInfo proposalInfo, @TarsHolder(name="iRetCode") Holder<java.lang.Integer> iRetCode);

	 int deleteProposal(@TarsMethodParameter(name="proposal_id")String proposal_id, @TarsHolder(name="iRetCode") Holder<java.lang.Integer> iRetCode);

	 int getProposalInfo(@TarsMethodParameter(name="proposal_id")String proposal_id, @TarsHolder(name="proposalInfo") Holder<ProposalInfo> proposalInfo);

	 int createEventRecord(@TarsMethodParameter(name="wx_id")String wx_id, @TarsMethodParameter(name="event_id")String event_id);

	 int getEventRecords(@TarsMethodParameter(name="index")int index, @TarsMethodParameter(name="batch")int batch, @TarsMethodParameter(name="event_id")String event_id, @TarsHolder(name="nextIndex") Holder<java.lang.Integer> nextIndex, @TarsHolder(name="recordList") Holder<java.util.List<EventRecord>> recordList);

	 int deleteEventRecord(@TarsMethodParameter(name="event_id")String event_id, @TarsMethodParameter(name="wx_id")String wx_id, @TarsHolder(name="iRetCode") Holder<java.lang.Integer> iRetCode);

	 int insertData(@TarsMethodParameter(name="sTableName")String sTableName, @TarsMethodParameter(name="sColumns")java.util.List<Column> sColumns);

	 int queryData(@TarsMethodParameter(name="sTableName")String sTableName, @TarsMethodParameter(name="sColumns")java.util.List<String> sColumns, @TarsMethodParameter(name="sCondition")String sCondition, @TarsHolder(name="sRsp") Holder<java.util.List<java.util.Map<String, String>>> sRsp);

	 int getRecordCount(@TarsMethodParameter(name="sTableName")String sTableName, @TarsMethodParameter(name="sCondition")String sCondition, @TarsHolder(name="iCount") Holder<java.lang.Integer> iCount);
}
