// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package Java.eventgadget;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface EventManagerServant {

	 int GetPlanetList(@TarsMethodParameter(name="index")int index, @TarsMethodParameter(name="wxId")String wxId, @TarsHolder(name="nextIndex") Holder<java.lang.Integer> nextIndex, @TarsHolder(name="planetInfoList") Holder<java.util.List<PlanetInfo>> planetInfoList, @TarsHolder(name="RetCode") Holder<java.lang.Integer> RetCode);

	 int JoinPlanet(@TarsMethodParameter(name="wxId")String wxId, @TarsMethodParameter(name="planetId")String planetId, @TarsHolder(name="RetCode") Holder<java.lang.Integer> RetCode);

	 int CreateProposal(@TarsMethodParameter(name="wxId")String wxId, @TarsMethodParameter(name="proposalInfo")ProposalInfo proposalInfo, @TarsHolder(name="RetCode") Holder<java.lang.Integer> RetCode);

	 int GetProposalList(@TarsMethodParameter(name="index")int index, @TarsMethodParameter(name="wxId")String wxId, @TarsMethodParameter(name="planetId")String planetId, @TarsHolder(name="nextIndex") Holder<java.lang.Integer> nextIndex, @TarsHolder(name="proposalList") Holder<java.util.List<java.util.Map<String, String>>> proposalList);

	 int UpdateProposal(@TarsMethodParameter(name="proposalInfo")ProposalInfo proposalInfo, @TarsHolder(name="RetCode") Holder<java.lang.Integer> RetCode);

	 int DeleteProposal(@TarsMethodParameter(name="proposalId")String proposalId, @TarsHolder(name="RetCode") Holder<java.lang.Integer> RetCode);

	 int GetEventList(@TarsMethodParameter(name="index")int index, @TarsMethodParameter(name="wxId")String wxId, @TarsMethodParameter(name="planetId")String planetId, @TarsHolder(name="nextIndex") Holder<java.lang.Integer> nextIndex, @TarsHolder(name="eventList") Holder<java.util.List<java.util.Map<String, String>>> eventList);

	 int GetEventDetail(@TarsMethodParameter(name="eventId")String eventId, @TarsHolder(name="eventInfo") Holder<EventInfo> eventInfo);

	 int GetEventParticipant(@TarsMethodParameter(name="index")int index, @TarsMethodParameter(name="eventId")String eventId, @TarsHolder(name="nextIndex") Holder<java.lang.Integer> nextIndex, @TarsHolder(name="participantList") Holder<java.util.List<EventRecord>> participantList);
}
