// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package Java.eventgadget;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class EventRecord {

	@TarsStructProperty(order = 0, isRequire = true)
	public String wx_id = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String user_name = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public String record_time = "";

	public String getWx_id() {
		return wx_id;
	}

	public void setWx_id(String wx_id) {
		this.wx_id = wx_id;
	}

	public String getUser_name() {
		return user_name;
	}

	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}

	public String getRecord_time() {
		return record_time;
	}

	public void setRecord_time(String record_time) {
		this.record_time = record_time;
	}

	public EventRecord() {
	}

	public EventRecord(String wx_id, String user_name, String record_time) {
		this.wx_id = wx_id;
		this.user_name = user_name;
		this.record_time = record_time;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(wx_id);
		result = prime * result + TarsUtil.hashCode(user_name);
		result = prime * result + TarsUtil.hashCode(record_time);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof EventRecord)) {
			return false;
		}
		EventRecord other = (EventRecord) obj;
		return (
			TarsUtil.equals(wx_id, other.wx_id) &&
			TarsUtil.equals(user_name, other.user_name) &&
			TarsUtil.equals(record_time, other.record_time) 
		);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("EventRecord(");
		sb.append("wx_id:");
		if (this.wx_id == null) {
			sb.append("null");
		} else {
			sb.append(this.wx_id);
		}
		sb.append(", ");
		sb.append("user_name:");
		if (this.user_name == null) {
			sb.append("null");
		} else {
			sb.append(this.user_name);
		}
		sb.append(", ");
		sb.append("record_time:");
		if (this.record_time == null) {
			sb.append("null");
		} else {
			sb.append(this.record_time);
		}
		sb.append(")");
		return sb.toString();
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(wx_id, 0);
		_os.write(user_name, 1);
		_os.write(record_time, 2);
	}


	public void readFrom(TarsInputStream _is) {
		this.wx_id = _is.readString(0, true);
		this.user_name = _is.readString(1, true);
		this.record_time = _is.readString(2, true);
	}

}
