// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package Java.eventgadget;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class EventInfo {

	@TarsStructProperty(order = 0, isRequire = true)
	public String event_id = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String name = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public String planet_id = "";
	@TarsStructProperty(order = 3, isRequire = true)
	public String location = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public String create_time = "";
	@TarsStructProperty(order = 5, isRequire = false)
	public String start_time = "";
	@TarsStructProperty(order = 6, isRequire = false)
	public String stop_time = "";
	@TarsStructProperty(order = 7, isRequire = false)
	public String content = "";

	public String getEvent_id() {
		return event_id;
	}

	public void setEvent_id(String event_id) {
		this.event_id = event_id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPlanet_id() {
		return planet_id;
	}

	public void setPlanet_id(String planet_id) {
		this.planet_id = planet_id;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getCreate_time() {
		return create_time;
	}

	public void setCreate_time(String create_time) {
		this.create_time = create_time;
	}

	public String getStart_time() {
		return start_time;
	}

	public void setStart_time(String start_time) {
		this.start_time = start_time;
	}

	public String getStop_time() {
		return stop_time;
	}

	public void setStop_time(String stop_time) {
		this.stop_time = stop_time;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public EventInfo() {
	}

	public EventInfo(String event_id, String name, String planet_id, String location, String create_time, String start_time, String stop_time, String content) {
		this.event_id = event_id;
		this.name = name;
		this.planet_id = planet_id;
		this.location = location;
		this.create_time = create_time;
		this.start_time = start_time;
		this.stop_time = stop_time;
		this.content = content;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(event_id);
		result = prime * result + TarsUtil.hashCode(name);
		result = prime * result + TarsUtil.hashCode(planet_id);
		result = prime * result + TarsUtil.hashCode(location);
		result = prime * result + TarsUtil.hashCode(create_time);
		result = prime * result + TarsUtil.hashCode(start_time);
		result = prime * result + TarsUtil.hashCode(stop_time);
		result = prime * result + TarsUtil.hashCode(content);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof EventInfo)) {
			return false;
		}
		EventInfo other = (EventInfo) obj;
		return (
			TarsUtil.equals(event_id, other.event_id) &&
			TarsUtil.equals(name, other.name) &&
			TarsUtil.equals(planet_id, other.planet_id) &&
			TarsUtil.equals(location, other.location) &&
			TarsUtil.equals(create_time, other.create_time) &&
			TarsUtil.equals(start_time, other.start_time) &&
			TarsUtil.equals(stop_time, other.stop_time) &&
			TarsUtil.equals(content, other.content) 
		);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("EventInfo(");
		sb.append("event_id:");
		if (this.event_id == null) {
			sb.append("null");
		} else {
			sb.append(this.event_id);
		}
		sb.append(", ");
		sb.append("name:");
		if (this.name == null) {
			sb.append("null");
		} else {
			sb.append(this.name);
		}
		sb.append(", ");
		sb.append("planet_id:");
		if (this.planet_id == null) {
			sb.append("null");
		} else {
			sb.append(this.planet_id);
		}
		sb.append(", ");
		sb.append("location:");
		if (this.location == null) {
			sb.append("null");
		} else {
			sb.append(this.location);
		}
		sb.append(", ");
		sb.append("create_time:");
		if (this.create_time == null) {
			sb.append("null");
		} else {
			sb.append(this.create_time);
		}
		sb.append(", ");
		sb.append("start_time:");
		if (this.start_time == null) {
			sb.append("null");
		} else {
			sb.append(this.start_time);
		}
		sb.append(", ");
		sb.append("stop_time:");
		if (this.stop_time == null) {
			sb.append("null");
		} else {
			sb.append(this.stop_time);
		}
		sb.append(", ");
		sb.append("content:");
		if (this.content == null) {
			sb.append("null");
		} else {
			sb.append(this.content);
		}
		sb.append(")");
		return sb.toString();
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(event_id, 0);
		if (null != name) {
			_os.write(name, 1);
		}
		_os.write(planet_id, 2);
		_os.write(location, 3);
		if (null != create_time) {
			_os.write(create_time, 4);
		}
		if (null != start_time) {
			_os.write(start_time, 5);
		}
		if (null != stop_time) {
			_os.write(stop_time, 6);
		}
		if (null != content) {
			_os.write(content, 7);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.event_id = _is.readString(0, true);
		this.name = _is.readString(1, false);
		this.planet_id = _is.readString(2, true);
		this.location = _is.readString(3, true);
		this.create_time = _is.readString(4, false);
		this.start_time = _is.readString(5, false);
		this.stop_time = _is.readString(6, false);
		this.content = _is.readString(7, false);
	}

}
