// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package Java.eventgadget;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class PlanetInfo {

	@TarsStructProperty(order = 0, isRequire = true)
	public String planet_id = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String name = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public String population = "";
	@TarsStructProperty(order = 3, isRequire = true)
	public String create_time = "";
	@TarsStructProperty(order = 4, isRequire = true)
	public String introduction = "";

	public String getPlanet_id() {
		return planet_id;
	}

	public void setPlanet_id(String planet_id) {
		this.planet_id = planet_id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPopulation() {
		return population;
	}

	public void setPopulation(String population) {
		this.population = population;
	}

	public String getCreate_time() {
		return create_time;
	}

	public void setCreate_time(String create_time) {
		this.create_time = create_time;
	}

	public String getIntroduction() {
		return introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public PlanetInfo() {
	}

	public PlanetInfo(String planet_id, String name, String population, String create_time, String introduction) {
		this.planet_id = planet_id;
		this.name = name;
		this.population = population;
		this.create_time = create_time;
		this.introduction = introduction;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(planet_id);
		result = prime * result + TarsUtil.hashCode(name);
		result = prime * result + TarsUtil.hashCode(population);
		result = prime * result + TarsUtil.hashCode(create_time);
		result = prime * result + TarsUtil.hashCode(introduction);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof PlanetInfo)) {
			return false;
		}
		PlanetInfo other = (PlanetInfo) obj;
		return (
			TarsUtil.equals(planet_id, other.planet_id) &&
			TarsUtil.equals(name, other.name) &&
			TarsUtil.equals(population, other.population) &&
			TarsUtil.equals(create_time, other.create_time) &&
			TarsUtil.equals(introduction, other.introduction) 
		);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("PlanetInfo(");
		sb.append("planet_id:");
		if (this.planet_id == null) {
			sb.append("null");
		} else {
			sb.append(this.planet_id);
		}
		sb.append(", ");
		sb.append("name:");
		if (this.name == null) {
			sb.append("null");
		} else {
			sb.append(this.name);
		}
		sb.append(", ");
		sb.append("population:");
		if (this.population == null) {
			sb.append("null");
		} else {
			sb.append(this.population);
		}
		sb.append(", ");
		sb.append("create_time:");
		if (this.create_time == null) {
			sb.append("null");
		} else {
			sb.append(this.create_time);
		}
		sb.append(", ");
		sb.append("introduction:");
		if (this.introduction == null) {
			sb.append("null");
		} else {
			sb.append(this.introduction);
		}
		sb.append(")");
		return sb.toString();
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(planet_id, 0);
		_os.write(name, 1);
		_os.write(population, 2);
		_os.write(create_time, 3);
		_os.write(introduction, 4);
	}


	public void readFrom(TarsInputStream _is) {
		this.planet_id = _is.readString(0, true);
		this.name = _is.readString(1, true);
		this.population = _is.readString(2, true);
		this.create_time = _is.readString(3, true);
		this.introduction = _is.readString(4, true);
	}

}
